name: analyze
on:
  push:
    branches: [ "main" ]
    
jobs:
  cppcheck:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install cppcheck
      run: |
        sudo apt update 
        sudo apt install -y cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --enable=all --force --template=gcc -I include src

  clang-tidy:
    runs-on: ubuntu-24.04
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        echo "VCPKG_ROOT=${{ github.workspace }}/vcpkg" >> $GITHUB_ENV

    - name: Create build directory
      run: cmake -E make_directory build

    - name: Configure 
      run: |
        cd build
        cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..

    - name: Run clang-tidy
      run: |
        clang-tidy-18 -p build/ -checks=*-clang-analyzer-* (CHANGE TO ACTUAL FILES)src/*.cpp include/*.hpp
